# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:mysql://banking-db:3306/bankdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JWT settings
# Generate a real secret with: openssl rand -base64 64
# DO NOT use this value in production
app.jwt.secret=IZXYHmwcMmRNoLh+Vv6aE9n0m6667FPpzAr1v99R6ZErGpF9s5bI1WLlMnykCvV5BdsW9IP07t2frm6C+TQJdg==
app.jwt.expiration-ms=3600000

# Logging
logging.level.org.springframework.security=DEBUG