# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://banking-db:3306/bankdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.application.name=banking-service

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.migrations=classpath:db/migration

# JWT settings
app.jwt.expiration-ms=3600000

app.auth.jwks-uri=http://auth-service:8081/.well-known/jwks.json

# Logging
logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=${spring.application.name}